---

name: 'Register Environment'
description: 'Register Azure Machine Learning environment'

inputs:
  environment_file:
    description: 'Path to the environment file'
    required: true
  resource_group:
    description: 'Resource Group'     
    required: true
    type: string
  workspace_name:
    description: 'Workspace Name'     
    required: true
    type: string    
  creds:
    description: 'Azure credentials'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}

    - name: Install Azure ML extension
      run: |
        az extension add -n ml -y
      shell: bash

    - name: Update Azure ML extension
      run: |
        az extension update -n ml
      shell: bash

    - name: Create environment from file with conda
      run: |
        az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
      shell: bash
