name: deploy-model-training-pipeline


on: 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'mlops-rg'
      aml_workspace:
        description: 'AML workspace name'
        required: true
        default: 'mlops-aml'
jobs:
  # get-config:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     config: ${{ steps.load-config.outputs.config }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Load config
  #       id: load-config
  #       uses: docker://ghcr.io/yodobrin/mlops-v2/get-config-action:1.0.0
  #       with:
  #         file_name: ./.github/workflows/variables.yml
  # # connect-to-workspace:
  # #   needs: get-config
  # #   runs-on: ubuntu-latest
  # #   outputs:
  # #     workspace: ${{ steps.connect.outputs.workspace }}
  # #   steps:
  # #     - name: Checkout repository
  # #       uses: actions/checkout@v2
  # #     - name: Connect to workspace
  # #       id: connect
  # #       uses: ./.github/actions/connect-to-workspace
  # #       with:
  # #         resource_group: ${{ needs.get-config.outputs.resource_group }}
  # #         workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
  # #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  register-environment:
      # needs: get-config
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Register Environment
          uses: ./.github/actions/register-environment
          with:
            environment_file: mlops/azureml/train/train-env.yml
            resource_group: ${{ inputs.resource_group }}
            workspace_name: ${{ inputs.aml_workspace }}  
            creds: ${{ secrets.AZURE_CREDENTIALS }}
