name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.load-config.outputs.config }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Load config
        id: load-config
        uses: docker://ghcr.io/yodobrin/mlops-v2/get-config-action:1.0.0
        with:
          file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: ./.github/workflows/common/register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
