name: deploy-model-training-pipeline


on: 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-ydamlv12-yd202304dev'
      aml_workspace:
        description: 'AML workspace name'
        required: true
        default: 'mlw-ydamlv12-yd202304dev'
      cluster_name:
        description: 'AML compute cluster name'
        required: true
        default: 'cpu-cluster'
jobs:

  register-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Register Environment
          uses: ./.github/actions/register-environment
          with:
            environment_file: mlops/azureml/train/train-env.yml
            resource_group: ${{ inputs.resource_group }}
            workspace_name: ${{ inputs.aml_workspace }}  
            creds: ${{ secrets.AZURE_CREDENTIALS }}
  create-compute:
    runs-on: ubuntu-latest
    needs: register-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Compute
        uses: ./.github/actions/create-compute
        with:
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }} 
          compute_name: ${{ inputs.cluster_name }} 
          cluster_size: 4
          node_sku: Standard_DS3_v2
          creds: ${{ secrets.AZURE_CREDENTIALS }}   
  run-pipeline:
    runs-on: ubuntu-latest
    needs: [register-environment, create-compute]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Pipeline
        uses: ./.github/actions/run-pipeline
        with:
          resource_group: ${{ inputs.resource_group }}
          workspace_name: ${{ inputs.aml_workspace }} 
          creds: ${{ secrets.AZURE_CREDENTIALS }}   
          parameters: ./mlops/azureml/train/pipeline.yml

