name: read-yaml
  #      # Global
  # ap_vm_image: ubuntu-20.04

  # namespace: spmlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  # postfix: 4200
  # location: northeurope
  # environment: dev
  # enable_aml_computecluster: true
  # enable_monitoring: false

  # # DO NOT TOUCH

  # # For pipeline reference
  # resource_group: rg-$(namespace)-$(postfix)$(environment)
  # aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  # application_insights: mlw-$(namespace)-$(postfix)$(environment)
  # key_vault: kv-$(namespace)-$(postfix)$(environment)
  # container_registry: cr$(namespace)$(postfix)$(environment)
  # storage_account: st$(namespace)$(postfix)$(environment)

on:
  workflow_call:
    inputs:
      location:
        description: "The resource group to use"
        default: 'northeurope'
        required: true
        type: string
      namespace:
        description: "Namespace of the resources"
        default: "spmlopsv2"
        required: true
        type: string
      postfix:
        description: "Postfix for the resource names"
        default: 4200
        required: true
        type: number
      environment:
        description: "Environment"
        default: "dev"
        required: true
        type: string
      enable_aml_computecluster:
        description: "Boolean to decide whether to deploy an AML compute cluster or not"
        default: true
        required: true
        type: boolean
      enable_monitoring:
        description: "Boolean to decide whether to enable monitoring"
        default: false
        required: true
        type: boolean
      resource_group:
        description: "The resource group to use"
        default: rg-$(namespace)-$(postfix)$(environment)
        required: true
        type: string
      aml_workspace:
        description: "The aml_workspace to use"
        default: mlw-$(namespace)-$(postfix)$(environment)
        required: true
        type: string
      bep:
        description: "The batch endpoint"
        default: bep-$(namespace)-$(postfix)$(environment)
        required: true
        type: string
      oep:
        description: "The online endpoint"
        default: oep-$(namespace)-$(postfix)$(environment)
        required: true
        type: string
    outputs:
      location:
        description: "The resource group to use"
        value: ${{ jobs.read-yaml.outputs.location }}
      namespace:
        description: "Namespace of the resources"
        value: ${{ jobs.read-yaml.outputs.namespace }}
      postfix:
        description: "Postfix for the resource names"
        value: ${{ jobs.read-yaml.outputs.postfix }}
      environment:
        description: "Environment"
        value: ${{ jobs.read-yaml.outputs.environment }}
      enable_aml_computecluster:
        description: "Boolean to decide whether to deploy an AML compute cluster or not"
        value: ${{ jobs.read-yaml.outputs.enable_aml_computecluster }}
      enable_monitoring:
        description: "Boolean to decide whether to enable monitoring"
        value: ${{ jobs.read-yaml.outputs.enable_monitoring }}
      resource_group:
        description: "The resource group to use"
        value: ${{ jobs.read-yaml.outputs.resource_group }}
      aml_workspace:
        description: "The aml_workspace to use"
        value: ${{ jobs.read-yaml.outputs.aml_workspace }}
      bep:
        description: "The batch endpoint"
        value: ${{ jobs.read-yaml.outputs.bep }}
      oep:
        description: "The online endpoint"
        value: ${{ jobs.read-yaml.outputs.oep }}

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs:
      location: ${{  steps.read_action_js.outputs.location }}
      namespace: ${{  steps.read_action_js.outputs.namespace }}
      postfix: ${{  steps.read_action_js.outputs.postfix }}
      environment: ${{  steps.read_action_js.outputs.environment }}
      enable_aml_computecluster: ${{  steps.read_action_js.outputs.enable_aml_computecluster }}
      enable_monitoring: ${{  steps.read_action_js.outputs.enable_monitoring }}
      resource_group: ${{  steps.read_action_js.outputs.resource_group }}
      aml_workspace: ${{  steps.read_action_js.outputs.aml_workspace }}
      # bep: ${{  steps.read_action_js.outputs.bep }}
      # oep: ${{  steps.read_action_js.outputs.oep }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Echo step output
        run: echo "The location is ${{ outputs.location }}"
